### ISSUE TITLE
[Bug] Icon not showing up in storybook toolbar

### ISSUE THREAD

**Issue by ktmDeveloper** [storybookjs/addon-measure#12]
Hello,

The icon for this addon is not showing up in my toolbar. I have pasted the screenshot below. The feature is working as expected, it is just that the icon is missing.

Thanks

![image](https://user-images.githubusercontent.com/8963447/121946565-ea0c3380-cd09-11eb-84e8-61cd257b6563.png)

**Comment by winkerVSbecks** [comment]
@ktmDeveloper this addon requires Storybook 6.3. Please ensure you are using the Storybook 6.3 beta.

**Comment by ktmDeveloper** [comment]
@winkerVSbecks yup, that fixed it. Thanks for the quick response. Appreciate it.
