### ISSUE TITLE
[Bug] addon-measure breaks alt functionality on Windows

### ISSUE THREAD

**Issue by bladeSk** [storybookjs/addon-measure#15]
### Describe the bug

The plugin breaks the original alt-key functionality - ie. displaying the browser menu on Windows. Another related issue is that the plugin gets activated when alt-tabbing to a different window and stays activated when returning back, which makes it incredibly annoying.

### Expected behavior

Use a different key. At least on Windows.

### Environment

 - OS: Windows 10
 - Browser (if applicable): Chrome
 - Browser version (if applicable): 91
 - Storybook: 6.3.0 with addon-essentials

### Workaround
Replace this in `.storybook/main.js`:
```js
addons: [
  '@storybook/addon-essentials',
]
```

With this:
```js
addons: [
  {
    name: '@storybook/addon-essentials',
    options: { measure: false },
  },
]
```

**Comment by winkerVSbecks** [comment]
@bladeSk do other Storybook shortcuts not interfere with this?`alt` key is used for a bunch of shortcuts already, to move between stories, etc.

**Comment by bladeSk** [comment]
Not that I know of. Shortcuts using `alt` in combination with other keys are fine, it's just alt by itself. The alt-tab problem is especially noticeable, as the selected story becomes unusable, unless you press alt or click the "measure" button. I've noticed this because v6.3.0 started to include addon-measure by default.

**Comment by winkerVSbecks** [comment]
Ok thanks, I am adding in the functionality that the addon will only trigger if you hold down alt. 
alt + anything else will no longer trigger.

**Comment by bladeSk** [comment]
I don't think that will work on Windows. I just tried binding `keydown` and `keyup` listeners to `document` and while `keydown` always works, the `keyup` handler never fires, when alt-tabbing out of Chrome. This results in the stuck key problem I described.

**Comment by winkerVSbecks** [comment]
Yea I'm tracking the blur event to disable the addon too. Do you want to give this a go and let me know how it works `npm i @storybook/addon-measure@1.3.0--canary.17.d15bbc2.0`

Or test it out here: https://60a5bbbc1be33900393f841a-zubivnfhke.chromatic.com/?path=/story/example-page--logged-in&globals=measureEnabled:false

**Comment by bladeSk** [comment]
The blur handler seems to have solved the addon getting stuck and Chrome menu can also be accessed. Good job with that. However, activating the addon is now somewhat buggy - measure can be only used once. Chrome menu gets focused after releasing `alt`  and then you need to either click in the page or press `esc`, to be able to use the measure tool again.

The alt key behavior is generally weird on Windows.

**Comment by winkerVSbecks** [comment]
Why is your Chrome menu getting focused? Isn't the shortcut for that `alt` + `e`?

**Comment by bladeSk** [comment]
`alt`+`e` opens the menu `alt` just focuses the button with three dots. Firefox behaves similarly.

**Comment by winkerVSbecks** [comment]
@bladeSk is `m` a good alternative? Hopefully that doesn't interfere with stuff on window

**Comment by toddbrady** [comment]
I would vote for `m` over the current functionality with `alt`.

**Comment by bladeSk** [comment]
`m` sounds fine, with the caveat, that a text field must not be focused for the shortcut to work.

**Comment by winkerVSbecks** [comment]
@bladeSk that is already the case. If a textfield is focused then the addon doesn't trigger.

**Comment by winkerVSbecks** [comment]
New update, with v2.0 you can tap <kbd>m</kbd> to toggle the addon on/off. 

This update should roll out in `@storybookjs/essentials` soon too.

**Comment by toddbrady** [comment]
@winkerVSbecks nice work! thanks for the update!
