### ISSUE TITLE
[Bug] fork and run

### ISSUE THREAD

**Issue by y-nk** [storybookjs/addon-measure#22]
### Steps to reproduce the behavior

1. Clone the repo
2. Change new package.json's name (`@storybook/addon-measure2`)
3. `yarn`
4. `yarn build`
5. add the cloned add-on in `.storybook/main.js` add-on section such as `  addons: ["@storybook/addon-measure2", ...]`
6. `yarn storybook`

### Expected behavior

It should work just fine

### Screenshots and/or logs

```
info => Loading presets
ERR! Addon value should end in /register OR it should be a valid preset https://storybook.js.org/docs/react/addons/writing-presets/
ERR! @storybook/addon-measure2
```

### Additional context

I'm running both in parallel (the addon and a separate storybook build) in a yarn workspaces monorepo.

**Comment by winkerVSbecks** [comment]
@y-nk that's expected behaviour. Storybook can't load up `@storybook/addon-measure2` because it's not a dependency of your project. Notice, https://github.com/storybookjs/addon-measure/blob/main/.storybook/main.js#L6 To work on the addon you have to reference the local preset file. 

If you are looking to build a new addon, check out https://github.com/storybookjs/addon-kit

**Comment by y-nk** [comment]
@winkerVSbecks 

> 5. add the cloned add-on in .storybook/main.js add-on section such as addons: ["@storybook/addon-measure2", ...]

...along with...

> I'm running both in parallel (the addon and a separate storybook build) in a yarn workspaces monorepo.

It _is_ indeed a dependency of the project.

**Comment by winkerVSbecks** [comment]
I'm not sure what your yarn workspaces monorepo setup is like. Saying `@storybook/addon-measure2` is a dependency can mean a few different things:
1. It's trying to use a local version
2. It's trying to use a published version (from npm)

I would confirm it is trying to use the local version. Then ensure that the local version has the build files in `dist. The error suggests that it can't find the preset. 

Happy to help out, but what you are trying to do is beyond the scope of this project. It's meant to be a stand alone addon.
