### ISSUE TITLE
[Bug] addon icon not visible in nuxt js storybook

### ISSUE THREAD

**Issue by claranceliberi** [storybookjs/addon-measure#9]
### 'addon-measure' icon not visible in nuxt.js
The add-on is working but not showing its icon on top in addon navbar

### Steps to reproduce the behavior

1. install add-on `yarn add -D @storybook/addon-measure`
2. add it in storybook options in `nuxt.config.js` 
```javascript
  storybook: {
    addons: [
      '@storybook/addon-notes',
      'storybook-dark-mode',
      "@storybook/addon-measure",
      'storybook-addon-outline'
    ]
  },
```
3. run storybook with the configured command to run it, on my app, 'yarn run storybook`
4.  then look up on the storybook web panel, on add on navbar

### Expected behavior

**add-on measure** the icon should be visible

### Screenshots and/or logs

![image](https://user-images.githubusercontent.com/60586899/120803880-4fab3380-c544-11eb-9314-8576ae0269b5.png)

### Environment

 - OS: `Windows 10 Pro, build: 21390.1, version: Dev`
 - Node.js version: `v14.16.1`
 - NPM version: `7.12.0`
 - Yarn version : `1.22.10`
 - Browser : `Google Chrome`
 - Browser version :  `Version 91.0.4472.77 (Official Build) (64-bit)`
 - Device : `Hp laptop`

**Comment by winkerVSbecks** [comment]
@claranceliberi are you using storybook 6.3 beta? This addon requires that you are on it.
